- hosts: master
  become: yes
  tasks:
    - name: Initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.1.3 >> cluster_initialized_2.txt
      args:
        chdir: $HOME
        creates: cluster_initialized_2.txt

    - name: Create .kube directory
      become: yes
      become_user: k8s
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      copy: 
        src: /etc/kubernetes/admin.conf
        dest: /home/k8s/.kube/config
        remote_src: yes
        owner: k8s

    - name: Install Pod Network
      become: yes
      become_user: k8s
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup_2.txt
      args: 
        chdir: $HOME
        creates: pod_network_setup_2.txt
